; Waveshare ESP32-S3-Touch-LCD-2.8C (ESP32-S3R8, 16MB Flash, 8MB PSRAM)
; https://www.waveshare.com/wiki/ESP32-S3-Touch-LCD-2.8C

[env:waveshare-esp32s3-28c]
platform = espressif32 @ ^6.9.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=1
  -I include
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.3
  adafruit/Adafruit SHT31 Library @ ^2.2.2
  adafruit/Adafruit BusIO @ ^1.16.1
  moononournation/GFX Library for Arduino @ 1.4.7
lib_ldf_mode = deep+
